/**
 * leaguesConfig.js — Maps internal league slugs to Sportsmonks IDs.
 *
 * All IDs discovered from Sportsmonks API:
 *   GET /leagues  → league IDs
 *   GET /seasons  → season IDs per league
 *   GET /stages   → stage IDs per season
 */

const LEAGUES = {
  ipl: {
    slug:      'ipl',
    name:      'Indian Premier League',
    short:     'IPL',
    season:    '2026',
    leagueId:  1,
    seasonId:  1795,
    stageId:   6468,   // Regular season (for standings)
    playoffId: 6469,
    flag:      '🏏',
    country:   'India',
    format:    'T20',
    sport:     'cricket',
  },
  bbl: {
    slug:      'bbl',
    name:      'Big Bash League',
    short:     'BBL',
    season:    '2025/26',
    leagueId:  5,
    seasonId:  1730,
    stageId:   6223,   // Regular season
    playoffId: 6224,
    flag:      '🦘',
    country:   'Australia',
    format:    'T20',
    sport:     'cricket',
  },
  psl: {
    slug:      'psl',
    name:      'Pakistan Super League',
    short:     'PSL',
    season:    '2026',
    leagueId:  8,
    seasonId:  1802,
    stageId:   6487,
    playoffId: 6488,
    flag:      '🟢',
    country:   'Pakistan',
    format:    'T20',
    sport:     'cricket',
  },
  bpl: {
    slug:      'bpl',
    name:      'Bangladesh Premier League',
    short:     'BPL',
    season:    '2025/26',
    leagueId:  9,
    seasonId:  1792,
    stageId:   6458,
    playoffId: 6459,
    flag:      '🟥',
    country:   'Bangladesh',
    format:    'T20',
    sport:     'cricket',
  },
  t20blast: {
    slug:      't20blast',
    name:      'T20 Blast',
    short:     'T20 Blast',
    season:    '2026',
    leagueId:  13,
    seasonId:  1788,
    stageId:   6451,
    playoffId: 6453,
    flag:      '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    country:   'England',
    format:    'T20',
    sport:     'cricket',
  },
  t20wc: {
    slug:      't20wc',
    name:      "ICC Men's T20 World Cup",
    short:     'T20 WC',
    season:    '2026',
    leagueId:  17,
    seasonId:  1770,
    stageId:   6442,   // Group A (first group stage)
    playoffId: 6448,   // Play Offs
    flag:      '🌍',
    country:   'International',
    format:    'T20',
    sport:     'cricket',
  },
  wwct20: {
    slug:      'wwct20',
    name:      "ICC Women's T20 World Cup",
    short:     'WWCT20',
    season:    '2026',
    leagueId:  16,
    seasonId:  1745,
    stageId:   null,   // auto-discovered by leagueService.resolveStageId
    playoffId: null,
    flag:      '🏏',
    country:   'World',
    format:    'T20',
    sport:     'cricket',
  },
  gsl: {
    slug:      'gsl',
    name:      'Global Super League',
    short:     'GSL',
    season:    '2026',
    leagueId:  426,
    seasonId:  1817,
    stageId:   6546,
    playoffId: 6547,
    flag:      '🌐',
    country:   'West Indies',
    format:    'T20',
    sport:     'cricket',
  },
  csa_t20: {
    slug:      'csa_t20',
    name:      'CSA T20 Challenge',
    short:     'CSA T20',
    season:    '2025/26',
    leagueId:  10,
    seasonId:  1769,
    stageId:   6380,
    playoffId: 6381,
    flag:      '🦁',
    country:   'South Africa',
    format:    'T20',
    sport:     'cricket',
  },
  supersmash: {
    slug:      'supersmash',
    name:      'Super Smash',
    short:     'SS',
    season:    '2025/26',
    leagueId:  6,
    seasonId:  1765,
    stageId:   null,
    playoffId: null,
    flag:      '🥝',
    country:   'New Zealand',
    format:    'T20',
    sport:     'cricket',
  },
  ashes: {
    slug:      'ashes',
    name:      'Ashes Series',
    short:     'Ashes',
    season:    '2025/26',
    leagueId:  12,
    seasonId:  1683,
    stageId:   null,
    playoffId: null,
    flag:      '🏺',
    country:   'England / Australia',
    format:    'Test',
    sport:     'cricket',
  },
  t20mumbai: {
    slug:      't20mumbai',
    name:      'T20 Mumbai',
    short:     'T20 Mum',
    season:    '2026',
    leagueId:  106,
    seasonId:  1818,
    stageId:   null,
    playoffId: null,
    flag:      '🏙',
    country:   'India',
    format:    'T20',
    sport:     'cricket',
  },
  t20blastw: {
    slug:      't20blastw',
    name:      "T20 Blast Women's",
    short:     'T20 Blast W',
    season:    '2026',
    leagueId:  428,
    seasonId:  1790,
    stageId:   null,
    playoffId: null,
    flag:      '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    country:   'England',
    format:    'T20',
    sport:     'cricket',
  },
  iml: {
    slug:      'iml',
    name:      'International Masters League',
    short:     'IML',
    season:    '2025/26',
    leagueId:  429,
    seasonId:  1700,
    stageId:   null,
    playoffId: null,
    flag:      '🌍',
    country:   'International',
    format:    'T20',
    sport:     'cricket',
  },
  ecsp: {
    slug:      'ecsp',
    name:      'ECS Portugal',
    short:     'ECS PT',
    season:    '2026',
    leagueId:  252,
    seasonId:  1809,
    stageId:   null,
    playoffId: null,
    flag:      '🇵🇹',
    country:   'Portugal',
    format:    'T10',
    sport:     'cricket',
  },
  triseries: {
    slug:      'triseries',
    name:      'Tri-Series',
    short:     'Tri',
    season:    '2026',
    leagueId:  35,
    seasonId:  1823,
    stageId:   null,
    playoffId: null,
    flag:      '🌏',
    country:   'International',
    format:    'T20I',
    sport:     'cricket',
  },
  // ── Leagues added for Highlightly coverage (no Sportsmonks IDs) ──
  sa20: {
    slug:    'sa20',
    name:    'SA20',
    short:   'SA20',
    season:  '2025',
    flag:    '🦁',
    country: 'South Africa',
    format:  'T20',
    sport:   'cricket',
  },
  lpl: {
    slug:    'lpl',
    name:    'Lanka Premier League',
    short:   'LPL',
    season:  '2026',
    flag:    '🦁',
    country: 'Sri Lanka',
    format:  'T20',
    sport:   'cricket',
  },
  mlc: {
    slug:    'mlc',
    name:    'Major League Cricket',
    short:   'MLC',
    season:  '2026',
    flag:    '🇺🇸',
    country: 'USA',
    format:  'T20',
    sport:   'cricket',
  },
  hundred_men: {
    slug:    'hundred_men',
    name:    "The Hundred Men's",
    short:   'Hundred',
    season:  '2026',
    flag:    '💯',
    country: 'England',
    format:  'T20',
    sport:   'cricket',
  },
  hundred_women: {
    slug:    'hundred_women',
    name:    "The Hundred Women's",
    short:   'Hundred W',
    season:  '2026',
    flag:    '💯',
    country: 'England',
    format:  'T20',
    sport:   'cricket',
  },
  // ── Indian domestic leagues (homeBundle: false — not fetched in home bundle) ──
  // These appear in the Matches tab league picker. Data comes from the
  // Highlightly warehouse populated by the 60-day sync + auto-discovery.
  tnpl: {
    slug:       'tnpl',
    name:       'Tamil Nadu Premier League',
    short:      'TNPL',
    season:     '2026',
    flag:       '🏏',
    country:    'India',
    format:     'T20',
    sport:      'cricket',
    homeBundle: false,
  },
  maharaja: {
    slug:       'maharaja',
    name:       'Maharaja T20 Trophy',
    short:      'Maharaja T20',
    season:     '2026',
    flag:       '👑',
    country:    'India',
    format:     'T20',
    sport:      'cricket',
    homeBundle: false,
  },
  jpl: {
    slug:       'jpl',
    name:       'Jharkhand Premier League',
    short:      'JPL',
    season:     '2026',
    flag:       '🏏',
    country:    'India',
    format:     'T20',
    sport:      'cricket',
    homeBundle: false,
  },
  mppl: {
    slug:       'mppl',
    name:       'Madhya Pradesh Premier League',
    short:      'MPPL',
    season:     '2026',
    flag:       '🏏',
    country:    'India',
    format:     'T20',
    sport:      'cricket',
    homeBundle: false,
  },
  wpl: {
    slug:       'wpl',
    name:       "Women's Premier League",
    short:      'WPL',
    season:     '2026',
    flag:       '🏏',
    country:    'India',
    format:     'T20',
    sport:      'cricket',
    homeBundle: false,
  },
  duleep: {
    slug:       'duleep',
    name:       'Duleep Trophy',
    short:      'Duleep',
    season:     '2026',
    flag:       '🏏',
    country:    'India',
    format:     'First Class',
    sport:      'cricket',
    homeBundle: false,
  },
  irani_cup: {
    slug:       'irani_cup',
    name:       'Irani Cup',
    short:      'Irani',
    season:     '2026',
    flag:       '🏏',
    country:    'India',
    format:     'First Class',
    sport:      'cricket',
    homeBundle: false,
  },
  smat: {
    slug:       'smat',
    name:       'Syed Mushtaq Ali Trophy',
    short:      'SMAT',
    season:     '2026',        // 2026-27 season starts Nov 2026
    flag:       '🏏',
    country:    'India',
    format:     'T20',
    sport:      'cricket',
    homeBundle: false,
  },
  vijay_hazare: {
    slug:       'vijay_hazare',
    name:       'Vijay Hazare Trophy',
    short:      'VHT',
    season:     '2026',        // 2026-27 season starts Dec 2026
    flag:       '🏏',
    country:    'India',
    format:     'List A',
    sport:      'cricket',
    homeBundle: false,
  },
  ranji: {
    slug:       'ranji',
    name:       'Ranji Trophy',
    short:      'Ranji',
    season:     '2026',        // 2026-27 season (Elite Phase 1 starts Oct 11)
    flag:       '🏆',
    country:    'India',
    format:     'First Class',
    sport:      'cricket',
    homeBundle: false,
  },
};

// ── Football leagues ──────────────────────────────────────────
// wc2026: served via football-data.org (free tier, dedicated service)
// isl, laliga: served via Highlightly API (same subscription as cricket)

const FOOTBALL_LEAGUES = {
  // ── Already active (home bundle) ─────────────────────────────
  wc2026: {
    slug:            'wc2026',
    name:            'FIFA World Cup 2026',
    short:           'WC 2026',
    season:          '2026',
    competitionCode: 'WC',   // football-data.org competition code
    flag:            '🏆',
    country:         'USA / Canada / Mexico',
    format:          '90min',
    sport:           'football',
  },
  isl: {
    slug:    'isl',
    name:    'Indian Super League',
    short:   'ISL',
    season:  '2026',
    flag:    '⚽',
    country: 'India',
    format:  '90min',
    sport:   'football',
  },
  premier_league: {
    slug:    'premier_league',
    name:    'Premier League',
    short:   'EPL',
    season:  '2026',
    flag:    '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    country: 'England',
    format:  '90min',
    sport:   'football',
  },
  laliga: {
    slug:    'laliga',
    name:    'La Liga',
    short:   'La Liga',
    season:  '2026',
    flag:    '🇪🇸',
    country: 'Spain',
    format:  '90min',
    sport:   'football',
  },
  bundesliga: {
    slug:    'bundesliga',
    name:    'Bundesliga',
    short:   'Bundesliga',
    season:  '2026',
    flag:    '🇩🇪',
    country: 'Germany',
    format:  '90min',
    sport:   'football',
  },
  serie_a: {
    slug:    'serie_a',
    name:    'Serie A',
    short:   'Serie A',
    season:  '2026',
    flag:    '🇮🇹',
    country: 'Italy',
    format:  '90min',
    sport:   'football',
  },
  ligue1: {
    slug:    'ligue1',
    name:    'Ligue 1',
    short:   'Ligue 1',
    season:  '2026',
    flag:    '🇫🇷',
    country: 'France',
    format:  '90min',
    sport:   'football',
  },
  ucl: {
    slug:    'ucl',
    name:    'UEFA Champions League',
    short:   'UCL',
    season:  '2026',
    flag:    '⭐',
    country: 'Europe',
    format:  '90min',
    sport:   'football',
  },
  uel: {
    slug:    'uel',
    name:    'UEFA Europa League',
    short:   'UEL',
    season:  '2026',
    flag:    '🟠',
    country: 'Europe',
    format:  '90min',
    sport:   'football',
  },

  // ── More European Leagues (homeBundle: false — matches tab only) ──
  eredivisie: {
    slug:       'eredivisie',
    name:       'Eredivisie',
    short:      'Eredivisie',
    season:     '2026',
    flag:       '🇳🇱',
    country:    'Netherlands',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  liga_portugal: {
    slug:       'liga_portugal',
    name:       'Primeira Liga',
    short:      'Liga PT',
    season:     '2026',
    flag:       '🇵🇹',
    country:    'Portugal',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  super_lig: {
    slug:       'super_lig',
    name:       'Süper Lig',
    short:      'Süper Lig',
    season:     '2026',
    flag:       '🇹🇷',
    country:    'Turkey',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  championship: {
    slug:       'championship',
    name:       'Championship',
    short:      'Championship',
    season:     '2026',
    flag:       '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    country:    'England',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  segunda: {
    slug:       'segunda',
    name:       'Segunda División',
    short:      'LaLiga 2',
    season:     '2026',
    flag:       '🇪🇸',
    country:    'Spain',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  ligue2: {
    slug:       'ligue2',
    name:       'Ligue 2',
    short:      'Ligue 2',
    season:     '2026',
    flag:       '🇫🇷',
    country:    'France',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },

  // ── Domestic Cups ─────────────────────────────────────────────
  fa_cup: {
    slug:       'fa_cup',
    name:       'FA Cup',
    short:      'FA Cup',
    season:     '2026',
    flag:       '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    country:    'England',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  league_cup: {
    slug:       'league_cup',
    name:       'League Cup',
    short:      'EFL Cup',
    season:     '2026',
    flag:       '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    country:    'England',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  copa_del_rey: {
    slug:       'copa_del_rey',
    name:       'Copa del Rey',
    short:      'Copa del Rey',
    season:     '2026',
    flag:       '🇪🇸',
    country:    'Spain',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  dfb_pokal: {
    slug:       'dfb_pokal',
    name:       'DFB Pokal',
    short:      'DFB Pokal',
    season:     '2026',
    flag:       '🇩🇪',
    country:    'Germany',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  coppa_italia: {
    slug:       'coppa_italia',
    name:       'Coppa Italia',
    short:      'Coppa Italia',
    season:     '2026',
    flag:       '🇮🇹',
    country:    'Italy',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },

  // ── Americas ──────────────────────────────────────────────────
  mls: {
    slug:       'mls',
    name:       'Major League Soccer',
    short:      'MLS',
    season:     '2026',
    flag:       '🇺🇸',
    country:    'USA',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  copa_america: {
    slug:       'copa_america',
    name:       'Copa America',
    short:      'Copa América',
    season:     '2024',
    flag:       '🌎',
    country:    'South America',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },

  // ── Asia ──────────────────────────────────────────────────────
  j_league: {
    slug:       'j_league',
    name:       'J1 League',
    short:      'J1 League',
    season:     '2026/27',
    flag:       '🇯🇵',
    country:    'Japan',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  k_league: {
    slug:       'k_league',
    name:       'K League 1',
    short:      'K League 1',
    season:     '2026',
    flag:       '🇰🇷',
    country:    'South Korea',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  i_league: {
    slug:       'i_league',
    name:       'I-League',
    short:      'I-League',
    season:     '2026',
    flag:       '🇮🇳',
    country:    'India',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  afc_asian_cup: {
    slug:       'afc_asian_cup',
    name:       'AFC Asian Cup',
    short:      'Asian Cup',
    season:     '2024',
    flag:       '🌏',
    country:    'Asia',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },

  // ── Oceania ───────────────────────────────────────────────────
  a_league: {
    slug:       'a_league',
    name:       'A-League',
    short:      'A-League',
    season:     '2026',
    flag:       '🇦🇺',
    country:    'Australia',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },

  // ── Middle East ───────────────────────────────────────────────
  saudi_pro: {
    slug:       'saudi_pro',
    name:       'Saudi Pro League',
    short:      'Saudi Pro',
    season:     '2026',
    flag:       '🇸🇦',
    country:    'Saudi Arabia',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },

  // ── International Tournaments ─────────────────────────────────
  euro: {
    slug:       'euro',
    name:       'UEFA European Championship',
    short:      'Euro',
    season:     '2024',
    flag:       '🌍',
    country:    'Europe',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
  afcon: {
    slug:       'afcon',
    name:       'Africa Cup of Nations',
    short:      'AFCON',
    season:     '2025',
    flag:       '🌍',
    country:    'Africa',
    format:     '90min',
    sport:      'football',
    homeBundle: false,
  },
};

const ALL_LEAGUES = { ...LEAGUES, ...FOOTBALL_LEAGUES };

function getLeague(slug) {
  return ALL_LEAGUES[slug] ?? null;
}

// Lookup by Sportsmonks league ID (cricket only)
function getLeagueBySmId(leagueId) {
  return Object.values(LEAGUES).find(l => l.leagueId === Number(leagueId)) ?? null;
}

// Lookup by Sportsmonks season ID (cricket only)
function getLeagueBySeasonId(seasonId) {
  return Object.values(LEAGUES).find(l => l.seasonId === Number(seasonId)) ?? null;
}

// Lookup football league by API-Football league ID
function getFootballLeague(slug) {
  return FOOTBALL_LEAGUES[slug] ?? null;
}

module.exports = { LEAGUES, FOOTBALL_LEAGUES, ALL_LEAGUES, getLeague, getLeagueBySmId, getLeagueBySeasonId, getFootballLeague };
